name: service_reminder
description: A new Flutter project.
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  introduction_screen: ^3.1.11
  persian_number_utility: ^1.1.3
  flutter_svg: ^2.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  hive_generator: ^2.0.1
  intl: ^0.18.1
  get: ^4.6.6
  shamsi_date: ^1.0.1
  double_back_to_close_app: ^2.1.0
  numberpicker: ^2.1.2
  # persian_datetimepickers: ^1.0.3+2
  # awesome_notifications: ^0.7.4+1
  # permission_handler: ^11.0.0
  animated_text_kit: ^4.2.2
  device_preview: ^1.1.0
  # table_calendar_jalali: ^1.0.1
  # persian_datetime_picker: ^2.6.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
flutter_gen:
  integrations:
    flutter_svg: true
flutter:
  uses-material-design: true

  assets:
  - assets/images/
  - assets/images/intro/
  - assets/svg/icons/
  - assets/svg/intro/

  fonts:
    - family: sans
      fonts:
        - asset: assets/fonts/sans_ultraLight.ttf
          weight: 200
        - asset: assets/fonts/sans_light.ttf
          weight: 300
        - asset: assets/fonts/sans.ttf
          weight: 500
        - asset: assets/fonts/sans_medium.ttf
          weight: 600
        - asset: assets/fonts/sans_bold.ttf
          weight: 700
        - asset: assets/fonts/sans_big.ttf
          weight: 900
    - family: digit
      fonts:
        - asset: assets/fonts/digit.otf
    - family: digital
      fonts:
        - asset: assets/fonts/digital.ttf
    - family: digital2
      fonts:
        - asset: assets/fonts/digital2.ttf